version: '3.6'
services:
  db-controle-financeiro:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "controle-financeiro"
    ports:
      - "3306:3306"  
  app-controle-financeiro:
    image: tomcat:9-slim
    depends_on:
      - db-controle-financeiro
    ports:
      - "8080:8080"
    volumes:
      - ./target/controle-financeiro-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/controle-financeiro.war
      